version: '3'
services:
  jwt-app:
    build: https://github.com/BNdungu/jwt-app.git
    environment:
      - PORT=4000
    # ports:
    #   - "5000:4000"

  nginx:
    build: ./nginx
    ports:
      - "80:80"
    environment:
      - SERVER_NAME=jwt-app.local

    